version: '3.4'
services:
 mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: primary_social
  volumes:
    - ./module/config/db_dump:/docker-entrypoint-initdb.d
